# Generated by Django 4.2.2 on 2023-06-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_product_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
    ]
